In [ ]:
# Apple Product Pricing SQL Analysis

## Project Overview

This project demonstrates SQL-based business analysis on Apple product pricing data.

The objective is to answer business questions using SQL instead of Python.

### Tools Used

- Google Colab
- SQLite
- SQL
- Pandas (Only for loading data)

### Dataset

cleaned_data.csv

In [1]:
import pandas as pd
import sqlite3

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
from google.colab import files

uploaded = files.upload()

Saving cleaned_data.csv to cleaned_data.csv

In [3]:
df = pd.read_csv("cleaned_data.csv")

df.head()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count,Price_Drop_USD,Price_Retention_Pct,Discount_Amount_USD
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,No Sale,In Stock,4.7,40,-6.81,101.587413,-6.864
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,No Sale,Out of Stock,4.6,84,-7.49,101.745921,-7.293
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,No Sale,In Stock,4.4,110,6.27,98.538462,6.435
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,No Sale,In Stock,4.8,111,4.00,99.067599,3.861
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,No Sale,In Stock,4.7,35,-7.22,101.682984,-7.293

In [4]:
conn = sqlite3.connect("apple_products.db")

In [5]:
df.to_sql(
    "AppleProducts",
    conn,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

Table created successfully!

In [6]:
query = """
SELECT *
FROM AppleProducts
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count,Price_Drop_USD,Price_Retention_Pct,Discount_Amount_USD
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,No Sale,In Stock,4.7,40,-6.81,101.587413,-6.864
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,No Sale,Out of Stock,4.6,84,-7.49,101.745921,-7.293
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,No Sale,In Stock,4.4,110,6.27,98.538462,6.435
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,No Sale,In Stock,4.8,111,4.00,99.067599,3.861
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,No Sale,In Stock,4.7,35,-7.22,101.682984,-7.293

In [7]:
query = """
SELECT DISTINCT Platform
FROM AppleProducts;
"""

pd.read_sql_query(query, conn)

   Platform
0  Flipkart
1    Amazon

In [8]:
query = """
SELECT COUNT(DISTINCT Platform) AS Total_Platforms
FROM AppleProducts;
"""

pd.read_sql_query(query, conn)

   Total_Platforms
0                2

In [9]:
query = """
SELECT
    Platform,
    AVG(Discount_Pct) AS Average_Discount
FROM AppleProducts
GROUP BY Platform
ORDER BY Average_Discount DESC;
"""

pd.read_sql_query(query, conn)

   Platform  Average_Discount
0    Amazon         21.515399
1  Flipkart         21.322461

In [10]:
query = """
SELECT
    Model_Name,
    Platform,
    Product_Category,
    Rating
FROM AppleProducts
WHERE Rating >= 4.8
ORDER BY Rating DESC;
"""

pd.read_sql_query(query, conn)

                        Model_Name  Platform Product_Category  Rating
0      Apple Watch Series 6 (44mm)    Amazon            Watch     4.9
1      Apple Watch Series 6 (44mm)  Flipkart            Watch     4.9
2                   iPhone 12 64GB  Flipkart           iPhone     4.9
3      Apple Watch Series 6 (44mm)    Amazon            Watch     4.9
4          iPad Air (4th Gen) 64GB    Amazon             iPad     4.9
...                            ...       ...              ...     ...
12979              iPhone 13 128GB    Amazon           iPhone     4.8
12980              iPhone 13 128GB    Amazon           iPhone     4.8
12981      iPhone 13 Pro Max 256GB  Flipkart           iPhone     4.8
12982              iPhone 14 128GB    Amazon           iPhone     4.8
12983              iPhone 17 128GB  Flipkart           iPhone     4.8

[12984 rows x 4 columns]

In [11]:
query = """
SELECT
    Model_Name,
    Product_Category,
    Platform,
    Current_Price_USD
FROM AppleProducts
WHERE Product_Category = 'iPhone';
"""

pd.read_sql_query(query, conn)

                Model_Name Product_Category  Platform  Current_Price_USD
0           iPhone 12 64GB           iPhone  Flipkart             794.53
1      iPhone 12 Pro 128GB           iPhone  Flipkart             994.04
2      iPhone 12 Pro 128GB           iPhone    Amazon            1002.99
3      iPhone 12 Pro 128GB           iPhone    Amazon            1018.59
4      iPhone 12 Pro 128GB           iPhone  Flipkart            1008.45
...                    ...              ...       ...                ...
28584      iPhone 17 128GB           iPhone  Flipkart             861.39
28585      iPhone 17 128GB           iPhone  Flipkart             832.50
28586      iPhone 17 128GB           iPhone    Amazon             657.30
28587      iPhone 17 128GB           iPhone  Flipkart             709.49
28588      iPhone 17 128GB           iPhone  Flipkart             834.95

[28589 rows x 4 columns]

In [12]:
query = """
SELECT
    Model_Name,
    Platform,
    Stock_Status
FROM AppleProducts
WHERE Stock_Status = 'Out of Stock';
"""

pd.read_sql_query(query, conn)

                        Model_Name  Platform  Stock_Status
0      Apple Watch Series 6 (44mm)  Flipkart  Out of Stock
1      Apple Watch Series 6 (44mm)    Amazon  Out of Stock
2      Apple Watch Series 6 (44mm)  Flipkart  Out of Stock
3      Apple Watch Series 6 (44mm)  Flipkart  Out of Stock
4      Apple Watch Series 6 (44mm)  Flipkart  Out of Stock
...                            ...       ...           ...
13470              iPhone 13 128GB    Amazon  Out of Stock
13471      iPhone 13 Pro Max 256GB  Flipkart  Out of Stock
13472      iPhone 13 Pro Max 256GB  Flipkart  Out of Stock
13473      iPhone 13 Pro Max 256GB    Amazon  Out of Stock
13474              iPhone 17 128GB    Amazon  Out of Stock

[13475 rows x 3 columns]

In [13]:
query = """
SELECT
    Model_Name,
    Platform,
    Rating
FROM AppleProducts
WHERE Product_Category = 'iPhone'
AND Rating > 4.7;
"""

pd.read_sql_query(query, conn)

                   Model_Name  Platform  Rating
0         iPhone 12 Pro 128GB  Flipkart     4.8
1              iPhone 12 64GB  Flipkart     4.9
2         iPhone 12 Pro 128GB    Amazon     4.8
3         iPhone 12 Pro 128GB  Flipkart     4.8
4         iPhone 12 Pro 128GB  Flipkart     4.8
...                       ...       ...     ...
4687          iPhone 13 128GB    Amazon     4.8
4688          iPhone 13 128GB    Amazon     4.8
4689  iPhone 13 Pro Max 256GB  Flipkart     4.8
4690          iPhone 14 128GB    Amazon     4.8
4691          iPhone 17 128GB  Flipkart     4.8

[4692 rows x 3 columns]

In [14]:
query = """
SELECT
    Model_Name,
    Discount_Pct,
    CASE
        WHEN Discount_Pct >= 30 THEN 'High Discount'
        WHEN Discount_Pct >= 15 THEN 'Medium Discount'
        ELSE 'Low Discount'
    END AS Discount_Category
FROM AppleProducts
LIMIT 20;
"""

pd.read_sql_query(query, conn)

                     Model_Name  Discount_Pct Discount_Category
0   Apple Watch Series 6 (44mm)          -1.6      Low Discount
1   Apple Watch Series 6 (44mm)          -1.7      Low Discount
2   Apple Watch Series 6 (44mm)           1.5      Low Discount
3   Apple Watch Series 6 (44mm)           0.9      Low Discount
4   Apple Watch Series 6 (44mm)          -1.7      Low Discount
5   Apple Watch Series 6 (44mm)          -1.7      Low Discount
6   Apple Watch Series 6 (44mm)          -0.9      Low Discount
7   Apple Watch Series 6 (44mm)          27.2   Medium Discount
8   Apple Watch Series 6 (44mm)          24.5   Medium Discount
9   Apple Watch Series 6 (44mm)           9.0      Low Discount
10  Apple Watch Series 6 (44mm)          10.2      Low Discount
11  Apple Watch Series 6 (44mm)          35.9     High Discount
12  Apple Watch Series 6 (44mm)          18.7   Medium Discount
13  Apple Watch Series 6 (44mm)          24.3   Medium Discount
14  Apple Watch Series 6 (44mm)          38.2     High Discount
15  Apple Watch Series 6 (44mm)          18.7   Medium Discount
16  Apple Watch Series 6 (44mm)          11.3      Low Discount
17  Apple Watch Series 6 (44mm)          17.3   Medium Discount
18  Apple Watch Series 6 (44mm)          18.8   Medium Discount
19  Apple Watch Series 6 (44mm)          28.1   Medium Discount

In [15]:
query = """
SELECT
    CASE
        WHEN Discount_Pct >= 30 THEN 'High Discount'
        WHEN Discount_Pct >= 15 THEN 'Medium Discount'
        ELSE 'Low Discount'
    END AS Discount_Category,

    AVG(Rating) AS Average_Rating

FROM AppleProducts

GROUP BY Discount_Category

ORDER BY Average_Rating DESC;
"""

pd.read_sql_query(query, conn)

  Discount_Category  Average_Rating
0      Low Discount        4.548916
1   Medium Discount        4.399216
2     High Discount        4.370891

In [16]:
query = """
SELECT
    Product_Category,
    Model_Name,
    Rating,

    RANK() OVER(
        PARTITION BY Product_Category
        ORDER BY Rating DESC
    ) AS Product_Rank

FROM AppleProducts;
"""

pd.read_sql_query(query, conn)

      Product_Category               Model_Name  Rating  Product_Rank
0                  Mac     MacBook Air M1 256GB     4.9             1
1                  Mac     MacBook Air M1 256GB     4.9             1
2                  Mac     MacBook Air M1 256GB     4.9             1
3                  Mac     MacBook Air M1 256GB     4.9             1
4                  Mac     MacBook Air M1 256GB     4.9             1
...                ...                      ...     ...           ...
79995           iPhone          iPhone 17 128GB     3.8         28096
79996           iPhone      iPhone 14 Pro 128GB     3.8         28096
79997           iPhone  iPhone 13 Pro Max 256GB     3.8         28096
79998           iPhone      iPhone 12 Pro 128GB     3.8         28096
79999           iPhone          iPhone 13 128GB     3.8         28096

[80000 rows x 4 columns]

In [17]:
query = """
WITH RankedProducts AS (

SELECT
    Product_Category,
    Model_Name,
    Rating,

    RANK() OVER(
        PARTITION BY Product_Category
        ORDER BY Rating DESC
    ) AS Product_Rank

FROM AppleProducts

)

SELECT *

FROM RankedProducts

WHERE Product_Rank = 1;
"""

pd.read_sql_query(query, conn)

     Product_Category            Model_Name  Rating  Product_Rank
0                 Mac  MacBook Air M1 256GB     4.9             1
1                 Mac  MacBook Air M1 256GB     4.9             1
2                 Mac  MacBook Air M1 256GB     4.9             1
3                 Mac  MacBook Air M1 256GB     4.9             1
4                 Mac  MacBook Air M1 256GB     4.9             1
...               ...                   ...     ...           ...
4328           iPhone       iPhone 13 128GB     4.9             1
4329           iPhone       iPhone 14 128GB     4.9             1
4330           iPhone       iPhone 16 128GB     4.9             1
4331           iPhone   iPhone 16 Pro 256GB     4.9             1
4332           iPhone   iPhone 12 Pro 128GB     4.9             1

[4333 rows x 4 columns]